# Generated by Django 2.2.6 on 2019-10-28 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Contact Name')),
                ('events', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Guest'),
        ),
    ]
